import type { BudgetResult, CompareDestination, SavedTrip } from '@/types'

// ── Mock budget result (Bangkok 7-day) ────────────────────────────
export const mockBangkokResult: BudgetResult = {
  id: 'bangkok-7d-1000',
  destination: 'Bangkok',
  country: 'Thailand',
  flag: '🇹🇭',
  totalBudget: 1000,
  currency: 'USD',
  days: 7,
  travelers: 1,
  style: 'budget',
  dailyBudget: 142,
  remainingBuffer: 100,
  verdict: 'yes',
  verdictMessage: 'You can comfortably do this trip with money to spare.',
  categories: [
    {
      id: 'accommodation',
      label: 'Accommodation',
      emoji: '🏨',
      amount: 280,
      percentage: 28,
      color: '#1F5641',
      description: '7 nights in a budget guesthouse or hostel private room',
    },
    {
      id: 'food',
      label: 'Food & Drinks',
      emoji: '🍽️',
      amount: 140,
      percentage: 14,
      color: '#DD7842',
      description: 'Street food, local restaurants, occasional café',
    },
    {
      id: 'transport',
      label: 'Transport',
      emoji: '🚌',
      amount: 70,
      percentage: 7,
      color: '#6F94A6',
      description: 'BTS Skytrain, tuk-tuks, river ferries',
    },
    {
      id: 'activities',
      label: 'Activities',
      emoji: '🎟️',
      amount: 150,
      percentage: 15,
      color: '#C29A3D',
      description: 'Grand Palace, temples, floating market, cooking class',
    },
    {
      id: 'emergency',
      label: 'Emergency Buffer',
      emoji: '🛡️',
      amount: 100,
      percentage: 10,
      color: '#B85148',
      description: 'Always keep 10% aside for unexpected costs',
    },
    {
      id: 'misc',
      label: 'Miscellaneous',
      emoji: '🛍️',
      amount: 160,
      percentage: 16,
      color: '#A8AB9D',
      description: 'Souvenirs, toiletries, SIM card, data, tips',
    },
  ],
  tips: [
    'Book a guesthouse in Banglamphu (Khao San area) — great value, central location',
    'Eat at local markets and street stalls — pad thai for ฿60, mango sticky rice for ฿80',
    'Use the BTS Skytrain + MRT + river ferry combo to avoid traffic and taxis',
    'Buy a 7-day SIM card for ฿300–500 with unlimited data',
    'Visit temples in the morning (cooler + less crowded)',
  ],
  neighborhoods: ['Banglamphu / Khao San', 'Silom', 'Sukhumvit On Nut', 'Ari'],
  localTips: [
    'Avoid metered taxis from Suvarnabhumi — use the Airport Rail Link instead (฿45)',
    'Negotiate tuk-tuk prices before boarding — ฿100-150 for short trips is fair',
    'Temple dress code: cover shoulders and knees (buy a sarong outside for ฿50)',
  ],
  createdAt: new Date().toISOString(),
}

// ── Comparison destinations ───────────────────────────────────────
export const compareDestinations: CompareDestination[] = [
  {
    id: 'vietnam',
    name: 'Vietnam',
    country: 'Vietnam',
    flag: '🇻🇳',
    avgDailyCost: 45,
    currency: 'USD',
    accommodation: { min: 10, max: 30 },
    food: { min: 5, max: 15 },
    transport: { min: 3, max: 10 },
    safetyScore: 85,
    internetScore: 90,
    weatherRating: 'Tropical',
    bestMonths: ['Feb', 'Mar', 'Apr', 'Dec'],
    tags: ['Beach', 'Culture', 'Food', 'Backpacker-friendly'],
  },
  {
    id: 'thailand',
    name: 'Thailand',
    country: 'Thailand',
    flag: '🇹🇭',
    avgDailyCost: 55,
    currency: 'USD',
    accommodation: { min: 12, max: 40 },
    food: { min: 8, max: 20 },
    transport: { min: 5, max: 15 },
    safetyScore: 82,
    internetScore: 85,
    weatherRating: 'Tropical',
    bestMonths: ['Nov', 'Dec', 'Jan', 'Feb'],
    tags: ['Temples', 'Beaches', 'Food', 'Nightlife'],
  },
  {
    id: 'turkey',
    name: 'Turkey',
    country: 'Turkey',
    flag: '🇹🇷',
    avgDailyCost: 60,
    currency: 'USD',
    accommodation: { min: 15, max: 50 },
    food: { min: 8, max: 20 },
    transport: { min: 5, max: 12 },
    safetyScore: 75,
    internetScore: 80,
    weatherRating: 'Mediterranean',
    bestMonths: ['Apr', 'May', 'Sep', 'Oct'],
    tags: ['History', 'Food', 'Landscapes', 'Culture'],
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    country: 'Indonesia',
    flag: '🇮🇩',
    avgDailyCost: 50,
    currency: 'USD',
    accommodation: { min: 8, max: 35 },
    food: { min: 5, max: 15 },
    transport: { min: 5, max: 15 },
    safetyScore: 80,
    internetScore: 75,
    weatherRating: 'Tropical',
    bestMonths: ['Jul', 'Aug', 'Apr', 'May'],
    tags: ['Beaches', 'Diving', 'Culture', 'Volcanoes'],
  },
  {
    id: 'georgia',
    name: 'Georgia',
    country: 'Georgia',
    flag: '🇬🇪',
    avgDailyCost: 40,
    currency: 'USD',
    accommodation: { min: 10, max: 35 },
    food: { min: 8, max: 18 },
    transport: { min: 3, max: 8 },
    safetyScore: 88,
    internetScore: 85,
    weatherRating: 'Continental',
    bestMonths: ['May', 'Jun', 'Sep', 'Oct'],
    tags: ['Hidden Gem', 'Wine', 'Hiking', 'History'],
  },
  {
    id: 'portugal',
    name: 'Portugal',
    country: 'Portugal',
    flag: '🇵🇹',
    avgDailyCost: 80,
    currency: 'USD',
    accommodation: { min: 20, max: 70 },
    food: { min: 12, max: 25 },
    transport: { min: 8, max: 20 },
    safetyScore: 92,
    internetScore: 88,
    weatherRating: 'Mediterranean',
    bestMonths: ['Mar', 'Apr', 'May', 'Sep', 'Oct'],
    tags: ['Beaches', 'History', 'Food', 'Digital Nomad'],
  },
]

// ── Saved trips ───────────────────────────────────────────────────
export const mockSavedTrips: SavedTrip[] = [
  {
    id: '1',
    name: 'Bangkok Adventure',
    destination: 'Bangkok',
    flag: '🇹🇭',
    budget: 1000,
    currency: 'USD',
    days: 7,
    createdAt: '2025-12-15T10:30:00Z',
    result: mockBangkokResult,
  },
  {
    id: '2',
    name: 'Hanoi on a Budget',
    destination: 'Hanoi',
    flag: '🇻🇳',
    budget: 600,
    currency: 'USD',
    days: 5,
    createdAt: '2025-12-10T14:00:00Z',
    result: {
      ...mockBangkokResult,
      id: 'hanoi-5d-600',
      destination: 'Hanoi',
      country: 'Vietnam',
      flag: '🇻🇳',
      totalBudget: 600,
      days: 5,
      dailyBudget: 120,
      verdict: 'yes',
      verdictMessage: 'Great choice! Hanoi is very affordable.',
    },
  },
]
