import type { BudgetResult, CompareDestination, SavedTrip, AccommodationCard, FoodPlace, ActivityRecommendation } from '@/types'

// ── Mock budget result (Bangkok 7-day) ────────────────────────────
export const mockBangkokResult: BudgetResult = {
  id: 'bangkok-7d-1000',
  destination: 'Bangkok',
  country: 'Thailand',
  flag: '🇹🇭',
  totalBudget: 1000,
  currency: 'USD',
  days: 7,
  travelers: 1,
  style: 'budget',
  dailyBudget: 142,
  remainingBuffer: 100,
  verdict: 'yes',
  verdictMessage: 'You can comfortably do this trip with money to spare.',
  categories: [
    {
      id: 'accommodation',
      label: 'Accommodation',
      emoji: '🏨',
      amount: 280,
      percentage: 28,
      color: '#1F5641',
      description: '7 nights in a budget guesthouse or hostel private room',
    },
    {
      id: 'food',
      label: 'Food & Drinks',
      emoji: '🍽️',
      amount: 140,
      percentage: 14,
      color: '#DD7842',
      description: 'Street food, local restaurants, occasional café',
    },
    {
      id: 'transport',
      label: 'Transport',
      emoji: '🚌',
      amount: 70,
      percentage: 7,
      color: '#6F94A6',
      description: 'BTS Skytrain, tuk-tuks, river ferries',
    },
    {
      id: 'activities',
      label: 'Activities',
      emoji: '🎟️',
      amount: 150,
      percentage: 15,
      color: '#C29A3D',
      description: 'Grand Palace, temples, floating market, cooking class',
    },
    {
      id: 'emergency',
      label: 'Emergency Buffer',
      emoji: '🛡️',
      amount: 100,
      percentage: 10,
      color: '#B85148',
      description: 'Always keep 10% aside for unexpected costs',
    },
    {
      id: 'misc',
      label: 'Miscellaneous',
      emoji: '🛍️',
      amount: 160,
      percentage: 16,
      color: '#A8AB9D',
      description: 'Souvenirs, toiletries, SIM card, data, tips',
    },
  ],
  tips: [
    'Book a guesthouse in Banglamphu (Khao San area) — great value, central location',
    'Eat at local markets and street stalls — pad thai for ฿60, mango sticky rice for ฿80',
    'Use the BTS Skytrain + MRT + river ferry combo to avoid traffic and taxis',
    'Buy a 7-day SIM card for ฿300–500 with unlimited data',
    'Visit temples in the morning (cooler + less crowded)',
  ],
  neighborhoods: ['Banglamphu / Khao San', 'Silom', 'Sukhumvit On Nut', 'Ari'],
  localTips: [
    'Avoid metered taxis from Suvarnabhumi — use the Airport Rail Link instead (฿45)',
    'Negotiate tuk-tuk prices before boarding — ฿100-150 for short trips is fair',
    'Temple dress code: cover shoulders and knees (buy a sarong outside for ฿50)',
  ],
  createdAt: new Date().toISOString(),
}

// ── Comparison destinations ───────────────────────────────────────
export const compareDestinations: CompareDestination[] = [
  {
    id: 'vietnam',
    name: 'Vietnam',
    country: 'Vietnam',
    flag: '🇻🇳',
    avgDailyCost: 45,
    currency: 'USD',
    accommodation: { min: 10, max: 30 },
    food: { min: 5, max: 15 },
    transport: { min: 3, max: 10 },
    safetyScore: 85,
    internetScore: 90,
    weatherRating: 'Tropical',
    bestMonths: ['Feb', 'Mar', 'Apr', 'Dec'],
    tags: ['Beach', 'Culture', 'Food', 'Backpacker-friendly'],
  },
  {
    id: 'thailand',
    name: 'Thailand',
    country: 'Thailand',
    flag: '🇹🇭',
    avgDailyCost: 55,
    currency: 'USD',
    accommodation: { min: 12, max: 40 },
    food: { min: 8, max: 20 },
    transport: { min: 5, max: 15 },
    safetyScore: 82,
    internetScore: 85,
    weatherRating: 'Tropical',
    bestMonths: ['Nov', 'Dec', 'Jan', 'Feb'],
    tags: ['Temples', 'Beaches', 'Food', 'Nightlife'],
  },
  {
    id: 'turkey',
    name: 'Turkey',
    country: 'Turkey',
    flag: '🇹🇷',
    avgDailyCost: 60,
    currency: 'USD',
    accommodation: { min: 15, max: 50 },
    food: { min: 8, max: 20 },
    transport: { min: 5, max: 12 },
    safetyScore: 75,
    internetScore: 80,
    weatherRating: 'Mediterranean',
    bestMonths: ['Apr', 'May', 'Sep', 'Oct'],
    tags: ['History', 'Food', 'Landscapes', 'Culture'],
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    country: 'Indonesia',
    flag: '🇮🇩',
    avgDailyCost: 50,
    currency: 'USD',
    accommodation: { min: 8, max: 35 },
    food: { min: 5, max: 15 },
    transport: { min: 5, max: 15 },
    safetyScore: 80,
    internetScore: 75,
    weatherRating: 'Tropical',
    bestMonths: ['Jul', 'Aug', 'Apr', 'May'],
    tags: ['Beaches', 'Diving', 'Culture', 'Volcanoes'],
  },
  {
    id: 'georgia',
    name: 'Georgia',
    country: 'Georgia',
    flag: '🇬🇪',
    avgDailyCost: 40,
    currency: 'USD',
    accommodation: { min: 10, max: 35 },
    food: { min: 8, max: 18 },
    transport: { min: 3, max: 8 },
    safetyScore: 88,
    internetScore: 85,
    weatherRating: 'Continental',
    bestMonths: ['May', 'Jun', 'Sep', 'Oct'],
    tags: ['Hidden Gem', 'Wine', 'Hiking', 'History'],
  },
  {
    id: 'portugal',
    name: 'Portugal',
    country: 'Portugal',
    flag: '🇵🇹',
    avgDailyCost: 80,
    currency: 'USD',
    accommodation: { min: 20, max: 70 },
    food: { min: 12, max: 25 },
    transport: { min: 8, max: 20 },
    safetyScore: 92,
    internetScore: 88,
    weatherRating: 'Mediterranean',
    bestMonths: ['Mar', 'Apr', 'May', 'Sep', 'Oct'],
    tags: ['Beaches', 'History', 'Food', 'Digital Nomad'],
  },
]

// ── Saved trips ───────────────────────────────────────────────────
export const mockSavedTrips: SavedTrip[] = [
  {
    id: '1',
    name: 'Bangkok Adventure',
    destination: 'Bangkok',
    flag: '🇹🇭',
    budget: 1000,
    currency: 'USD',
    days: 7,
    createdAt: '2025-12-15T10:30:00Z',
    result: mockBangkokResult,
  },
  {
    id: '2',
    name: 'Hanoi on a Budget',
    destination: 'Hanoi',
    flag: '🇻🇳',
    budget: 600,
    currency: 'USD',
    days: 5,
    createdAt: '2025-12-10T14:00:00Z',
    result: {
      ...mockBangkokResult,
      id: 'hanoi-5d-600',
      destination: 'Hanoi',
      country: 'Vietnam',
      flag: '🇻🇳',
      totalBudget: 600,
      days: 5,
      dailyBudget: 120,
      verdict: 'yes',
      verdictMessage: 'Great choice! Hanoi is very affordable.',
    },
  },
]

// ── Bangkok accommodation cards ───────────────────────────────────
export const bangkokAccommodations: AccommodationCard[] = [
  {
    id: 'nap-park',
    name: 'Nap Park Hostel',
    type: 'hostel',
    pricePerNight: 14,
    currency: 'USD',
    rating: 8.7,
    reviewCount: 2340,
    neighborhood: 'Banglamphu / Khao San',
    highlights: ['Free breakfast', 'Rooftop bar', '5 min walk to Khao San Rd'],
    bookingUrl:
      'https://www.booking.com/hotel/th/nap-park-hostel.html?aid=travio&label=travio-bangkok',
  },
  {
    id: 'lub-d-siam',
    name: "Lub d Bangkok Siam",
    type: 'hostel',
    pricePerNight: 22,
    currency: 'USD',
    rating: 9.0,
    reviewCount: 4810,
    neighborhood: 'Siam / City Centre',
    highlights: ['Attached to BTS Skytrain', 'Co-working space', 'Social events nightly'],
    bookingUrl:
      'https://www.booking.com/hotel/th/lub-d-bangkok-siam.html?aid=travio&label=travio-bangkok',
  },
  {
    id: 'atta-hostel',
    name: 'Atta Hostel',
    type: 'guesthouse',
    pricePerNight: 18,
    currency: 'USD',
    rating: 8.5,
    reviewCount: 1620,
    neighborhood: 'Banglamphu / Khao San',
    highlights: ['Private rooms available', 'Courtyard garden', 'Local tour desk'],
    bookingUrl:
      'https://www.booking.com/hotel/th/atta-hostel-bangkok.html?aid=travio&label=travio-bangkok',
  },
  {
    id: 'ibis-siam',
    name: 'ibis Bangkok Siam',
    type: 'budget-hotel',
    pricePerNight: 38,
    currency: 'USD',
    rating: 8.3,
    reviewCount: 6200,
    neighborhood: 'Siam / City Centre',
    highlights: ['24h reception', 'Air-conditioned rooms', 'Steps from MBK Center'],
    bookingUrl:
      'https://www.booking.com/hotel/th/ibis-bangkok-siam.html?aid=travio&label=travio-bangkok',
  },
]

// ── Bangkok food places ───────────────────────────────────────────
export const bangkokFoodPlaces: FoodPlace[] = [
  {
    id: 'jay-fai',
    name: 'Raan Jay Fai',
    cuisine: 'Thai Street Food',
    priceLevel: 3,
    avgMeal: 18,
    currency: 'USD',
    specialty: 'Crab omelette & drunken noodles',
    neighborhood: 'Banglamphu',
    tip: 'Michelin-starred street stall — queue early or book ahead',
  },
  {
    id: 'or-tor-kor',
    name: 'Or Tor Kor Market',
    cuisine: 'Thai Market',
    priceLevel: 1,
    avgMeal: 4,
    currency: 'USD',
    specialty: 'Mango sticky rice, fresh Thai dishes',
    neighborhood: 'Chatuchak',
    tip: 'Best mango sticky rice in Bangkok — ฿80–120',
  },
  {
    id: 'jok-prince',
    name: 'Jok Prince',
    cuisine: 'Thai Breakfast',
    priceLevel: 1,
    avgMeal: 3,
    currency: 'USD',
    specialty: 'Rice porridge (jok) with pork',
    neighborhood: 'Banglamphu',
    tip: 'Opens at 6am — popular with locals, cheap and filling',
  },
  {
    id: 'thip-samai',
    name: 'Thip Samai',
    cuisine: 'Thai',
    priceLevel: 1,
    avgMeal: 5,
    currency: 'USD',
    specialty: 'Pad thai wrapped in egg',
    neighborhood: 'Old City',
    tip: 'Queues form early — go before 6pm or after 9pm',
  },
  {
    id: 'chatuchak-food',
    name: 'Chatuchak Weekend Market',
    cuisine: 'Street Food',
    priceLevel: 1,
    avgMeal: 4,
    currency: 'USD',
    specialty: 'Grilled satay, coconut ice cream, fresh juices',
    neighborhood: 'Chatuchak',
    tip: 'Weekend only (Sat–Sun). 15,000 stalls — arrive before 11am',
  },
  {
    id: 'supanniga-eating',
    name: 'Supanniga Eating Room',
    cuisine: 'Thai Fine Casual',
    priceLevel: 2,
    avgMeal: 12,
    currency: 'USD',
    specialty: 'Eastern Thai cuisine, crab curry',
    neighborhood: 'Thonglor / Ekkamai',
    tip: 'Best mid-range Thai restaurant in town — book ahead',
  },
]

// ── Bangkok activities ─────────────────────────────────────────────
export const bangkokActivities: ActivityRecommendation[] = [
  {
    id: 'grand-palace',
    name: 'Grand Palace & Wat Phra Kaew',
    category: 'culture',
    price: 17,
    currency: 'USD',
    duration: '2–3 hours',
    description: 'The most iconic site in Bangkok. Includes the Emerald Buddha temple. Dress modestly — sarongs available at entrance.',
  },
  {
    id: 'wat-pho',
    name: 'Wat Pho (Reclining Buddha)',
    category: 'culture',
    price: 7,
    currency: 'USD',
    duration: '1 hour',
    description: '46m reclining Buddha and the birthplace of traditional Thai massage. Book a massage in the temple complex.',
  },
  {
    id: 'chao-phraya-ferry',
    name: 'Chao Phraya River Ferry',
    category: 'free',
    price: 0,
    currency: 'USD',
    duration: 'As long as you like',
    description: 'Hop on the orange-flag express boat and see riverside Bangkok for almost nothing. Best views at golden hour.',
  },
  {
    id: 'floating-market',
    name: 'Damnoen Saduak Floating Market',
    category: 'culture',
    price: 22,
    currency: 'USD',
    duration: 'Half day',
    description: 'Vendors selling food and crafts from boats on the canals. Best experienced early morning before the tour buses.',
    bookingUrl:
      'https://www.getyourguide.com/bangkok-l169/damnoen-saduak-floating-market-tour-tc24/?partner_id=travio',
  },
  {
    id: 'cooking-class',
    name: 'Thai Cooking Class',
    category: 'food-tour',
    price: 35,
    currency: 'USD',
    duration: '4 hours',
    description: 'Learn to cook 4 classic Thai dishes. Most classes include a market visit and a recipe book to take home.',
    bookingUrl:
      'https://www.getyourguide.com/bangkok-l169/thai-cooking-class-tc24/?partner_id=travio',
  },
  {
    id: 'lumpini-park',
    name: 'Lumpini Park',
    category: 'free',
    price: 0,
    currency: 'USD',
    duration: '1–2 hours',
    description: 'Bangkok\'s green lung. Watch locals doing morning tai chi, spot giant monitor lizards, and rent a paddleboat.',
  },
]
